export const data = [
    {
        id: '1',
        store_name: "Store 01",
        replenishment_date: '2024-05-22',
        confirmed_by: 'User A', 
        confirmation_date: '2024-05-27',
        replenishment_items: [
            {
                name: "Item 01",
                sku: "12345674589302-183594023-89123",
                proposed_quantity: 400,
                confirmed_quantity: 700,
                percentage_threshold_down: 100,
                percentage_threshold_up: 20
            },
            {
                name: "Item 0249380285739420",
                sku: "123456789123",
                proposed_quantity: 400,
                confirmed_quantity: 700,
                percentage_threshold_down: 100,
                percentage_threshold_up: 20
            },
            {
                name: "Item 03",
                sku: "123456789123",
                proposed_quantity: 400,
                confirmed_quantity: 700,
                percentage_threshold_down: 100,
                percentage_threshold_up: 20
            },
            {
                name: "Item 04",
                sku: "123456789123",
                proposed_quantity: 400,
                confirmed_quantity: 700,
                percentage_threshold_down: 100,
                percentage_threshold_up: 20
            },
            {
                name: "Item 05",
                sku: "123456789123",
                proposed_quantity: 400,
                confirmed_quantity: 700,
                percentage_threshold_down: 100,
                percentage_threshold_up: 20
            },
        ]
    },
    {
        id: '2',
        store_name: "Store 02",
        replenishment_date: '2024-05-23',
        replenishment_items: [
            {
                name: "Item 01",
                sku: "123456789123",
                proposed_quantity: 400,
                percentage_threshold_down: 100,
                percentage_threshold_up: 20
            },
            {
                name: "Item 02",
                sku: "123456789123",
                proposed_quantity: 400,
                percentage_threshold_down: 100,
                percentage_threshold_up: 20
            },
            {
                name: "Item 03",
                sku: "123456789123",
                proposed_quantity: 400,
                percentage_threshold_down: 100,
                percentage_threshold_up: 20
            },
            {
                name: "Item 04",
                sku: "123456789123",
                proposed_quantity: 400,
                percentage_threshold_down: 100,
                percentage_threshold_up: 20
            },
            {
                name: "Item 05",
                sku: "123456789123",
                proposed_quantity: 400,
                percentage_threshold_down: 100,
                percentage_threshold_up: 20
            },
        ]
    }
] 